### ISSUE TITLE
Is it possible to modify allowed_origins to allow any origin?

### ISSUE THREAD

**Issue by guest271314** [ericlaw1979/NativeMessagingDebugger#5]
Is it possible to modify or dynamically alter `"allowed_origins"` https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/extensions/api/messaging/native_messaging_host_manifest.cc;l=106-135;drc=a4d75ab5547e246d0f1a7cf01595c9825ab6f163 to allow connecting to Native Messaging host from any origin?

**Comment by ericlaw1979** [comment]
The |allowed_origins| field is in the Manifest JSON file, which you can edit with notepad. 

https://textslashplain.com/2022/01/08/debug-native-messaging/#:~:text=Open%20the%20manifest.json%20file%20using%20Notepad%20or%20a%20similar%20editor

**Comment by guest271314** [comment]
I mean modify (or otherwise workaround) the Chromium source code restriction that allows only protocol and extension ID origin `chrome-extension://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/`. For example, `"externally_connectable"` allows arbitrary websites to connect to the extension, not the Native Messaging host. Changing the origin to a non- chrome-extension://<id> origin in Native Messaging host manifest will not grant that site access to `runtime.connectNative()` or `runtime.sendNativeMessage()`. Did you read the linked source code?
